name: "Build and Deploy"
on:
  push:
    branches:
      - main
      - master
    paths-ignore:
      - .gitignore
      - README.md
      - LICENSE
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: read
  actions: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ${{ fromJSON('["ubuntu-latest", "self-hosted"]')[github.repository == 'github/docs-internal'] }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v3

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2
          bundler-cache: true

      - name: Build site
        run: bundle exec jekyll b -d "_site${{ steps.pages.outputs.base_path }}"
        env:
          JEKYLL_ENV: "production"

      - name: Test site
        run: |
          bundle exec htmlproofer _site --disable-external --checks --allow_hash_href

      - name: Check for Symlinks
        run: find _site -type l -exec ls -lah {} \;
        
      - name: Check for Hard Links
        run: find _site -type f -links +1

      - name: Remove symlinks
        run: find _site${{ steps.pages.outputs.base_path }} -type l -delete

      - name: Debug Build Output
        run: |
          ls -lah _site${{ steps.pages.outputs.base_path }}
          find _site${{ steps.pages.outputs.base_path }} -type l

      - name: Upload site artifact
        uses: actions/upload-artifact@v4
        with:
          path: "_site${{ steps.pages.outputs.base_path }}"
          name: github-pages

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
